title: Live Traffic Camera Analysis for Improved Navigation
description: Final project report for CS 6476 Computer Vision
author: Aishwarya Vijaykumar Sheelvant, Ayushi Chakrabarty, Kaustubh Odak
theme: jekyll-theme-cayman